import testApiTz  
vouchersExamples=[{
    id:1,
    "discountRate":5
},{
    id:2,
    "discountRate":5
},{
    id:3,
    "discountRate":5
}]
usersHavingVouchers=[{
    "address":"tz1gNDd435vP9qppaZMD5yuCkiQua9zSvcod",
    "voucherId":2
},
{
    "address":"tz1aMMC3iPNbfB7C8dNJ3Mf74L7xERXJ9A8q",
    "voucherId":3
}]
print(len(testApiTz.main()))