import json
import cashBackSender
import model
from pprint import pprint

def analyse(data):
    #pprint(data)
    for dat in data[0]["data"]:
        
        pprint(dat["amount"])

        try:
            if dat["parameter"]["entrypoint"]=="marketplace_transfer":
                print("hash marketplace transfer "+dat["hash"])
                initiator=dat["initiator"]["address"]
                print("model.eligible "+str(model.eligible()))
                print("length "+str(len(model.eligible())))
                elis=model.eligible()
                for u in range(0,len(elis)):
                    eli=elis[u]
                    print(str(eli)+" -- "+str(eli[0]))
                    if initiator==str(eli[0]):
                        amount=operationsVisualizer.getOperationAmount(dat["hash"])
                        hashOpe=dat["hash"]
                        entrypoint=dat["parameter"]["entrypoint"]
                        initiator=dat["initiator"]["address"]
                        print(hashOpe+" : "+entrypoint+" => "+" by "+initiator)
                        print(amount)
                        print(eli[1])
                        discount=eli[1]
                        print(discount)
                        print("discount "+str(discount)+"%")

                        model.addTx(hashOpe,eli[2],initiator,'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa',amount,dat["timestamp"])

                        cashBack=amount*eli[1]/100000000
                        print("cashBack: "+ str(amount*eli[1]/100000000))
                        print(str(cashBack)+" "+str(initiator))
                        print(cashBack,initiator)
                        
                        cashBackSender.cashbackSender(cashBack,initiator)
                print("fin loop")
        except KeyError:
            pass

testJson=[{'data': [{'allocationFee': 0,
            'amount': 1000000,
            'bakerFee': 2249,
            'block': 'BLoXbfT3kujJ4Dp1XSgtiKCHpgDqsFFDnkU5MivPJ1YpmNRdBRm',
            'counter': 10356524,
            'diffs': [{'action': 'update_key',
                       'bigmap': 56873,
                       'content': {'hash': 'expruSN9UTYux8uxcGANrKiLNeHpYA1J71UGuLiLiLzx6b5f5TngTR',
                                   'key': '1737',
                                   'value': {'category': 'unit',
                                             'on_sale': False,
                                             'owner': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im',
                                             'price': '1000000'}},
                       'path': 'listing'}],
            'gasLimit': 19410,
            'gasUsed': 8611,
            'hasInternals': True,
            'hash': 'oob4msjXo19SF14YoVmrJ9Bn59ocA8LBt46yTUEbCGDG7P36zWi',
            'id': 28793784,
            'level': 479458,
            'parameter': {'entrypoint': 'buy', 'value': ['1737']},
            'sender': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'status': 'applied',
            'storage': {'administrator': 'tz1fbKDvLgwjnuXDcVDUW8JdPTAsna5VhvKD',
                        'collector': 'tz1fbKDvLgwjnuXDcVDUW8JdPTAsna5VhvKD',
                        'fees': {'artifact': '600',
                                 'collectible': '600',
                                 'tezotop': '600',
                                 'ticket': '600',
                                 'unit': '600'},
                        'listing': 56873,
                        'metadata': 56874,
                        'nft_registry': 'KT1XKxvLdFzrhTF7KqLHFHuFhp4Ujq8x7vqA',
                        'paused': False,
                        'pending_admin': None,
                        'pool_share': '300',
                        'revenue_pool': 'KT1TeurBKDnhfyzUkeXWyCN9qbYpRRoFJNSF'},
            'storageFee': 0,
            'storageLimit': 0,
            'storageUsed': 0,
            'target': {'address': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa'},
            'timestamp': '2022-05-03T13:17:15Z',
            'type': 'transaction'},
           {'allocationFee': 0,
            'amount': 940000,
            'bakerFee': 0,
            'block': 'BLoXbfT3kujJ4Dp1XSgtiKCHpgDqsFFDnkU5MivPJ1YpmNRdBRm',
            'counter': 10356524,
            'gasLimit': 0,
            'gasUsed': 1420,
            'hasInternals': False,
            'hash': 'oob4msjXo19SF14YoVmrJ9Bn59ocA8LBt46yTUEbCGDG7P36zWi',
            'id': 28793785,
            'initiator': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'level': 479458,
            'nonce': 2,
            'sender': {'address': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa'},
            'status': 'applied',
            'storageFee': 0,
            'storageLimit': 0,
            'storageUsed': 0,
            'target': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'timestamp': '2022-05-03T13:17:15Z',
            'type': 'transaction'},
           {'allocationFee': 0,
            'amount': 0,
            'bakerFee': 0,
            'block': 'BLoXbfT3kujJ4Dp1XSgtiKCHpgDqsFFDnkU5MivPJ1YpmNRdBRm',
            'counter': 10356524,
            'diffs': [{'action': 'update_key',
                       'bigmap': 55191,
                       'content': {'hash': 'expruSN9UTYux8uxcGANrKiLNeHpYA1J71UGuLiLiLzx6b5f5TngTR',
                                   'key': '1737',
                                   'value': {'category': 'unit',
                                             'ints': {'accuracy': '15',
                                                      'attack': '12',
                                                      'defence': '9',
                                                      'exp': '0',
                                                      'hp': '18',
                                                      'mint_time': '1651495795',
                                                      'speed': '3'},
                                             'on_sale': False,
                                             'owner': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im',
                                             'sets': {},
                                             'strings': {'type': 'land'},
                                             'token_id': '1737',
                                             'uid': '834'}},
                       'path': 'token_attributes'},
                      {'action': 'update_key',
                       'bigmap': 55188,
                       'content': {'hash': 'expruBJMrUAbT7iX4zCW2VjN1HbJ1XyNurqtT3YWx3gnHiNmCe7Yb3',
                                   'key': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im',
                                           'nat': '1737'},
                                   'value': '1'},
                       'path': 'ledger'}],
            'gasLimit': 0,
            'gasUsed': 6609,
            'hasInternals': False,
            'hash': 'oob4msjXo19SF14YoVmrJ9Bn59ocA8LBt46yTUEbCGDG7P36zWi',
            'id': 28793786,
            'initiator': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'level': 479458,
            'nonce': 3,
            'parameter': {'entrypoint': 'marketplace_transfer',
                          'value': [{'from_': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im',
                                     'to_': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im',
                                     'token_id': '1737'}]},
            'sender': {'address': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa'},
            'status': 'applied',
            'storage': {'administrator': 'tz1fbKDvLgwjnuXDcVDUW8JdPTAsna5VhvKD',
                        'all_tokens': '1760',
                        'ledger': 55188,
                        'manager': 'KT1PP9kKPZfnF4WpjD8vWDZ8gdJoCBYdz2s7',
                        'marketplace': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa',
                        'metadata': 55189,
                        'minter': 'KT1ALweiYWmyfv6GgPKfoJkENRKCSkt9xYoz',
                        'operators': 55190,
                        'paused': False,
                        'pending_admin': None,
                        'token_attributes': 55191,
                        'token_metadata': 55192,
                        'uids': {'artifact': '603',
                                 'collectible': '125',
                                 'tezotop': '75',
                                 'ticket': '101',
                                 'unit': '856'}},
            'storageFee': 0,
            'storageLimit': 0,
            'storageUsed': 0,
            'target': {'address': 'KT1XKxvLdFzrhTF7KqLHFHuFhp4Ujq8x7vqA'},
            'timestamp': '2022-05-03T13:17:15Z',
            'type': 'transaction'},
           {'allocationFee': 0,
            'amount': 1800,
            'bakerFee': 0,
            'block': 'BLoXbfT3kujJ4Dp1XSgtiKCHpgDqsFFDnkU5MivPJ1YpmNRdBRm',
            'counter': 10356524,
            'gasLimit': 0,
            'gasUsed': 1252,
            'hasInternals': False,
            'hash': 'oob4msjXo19SF14YoVmrJ9Bn59ocA8LBt46yTUEbCGDG7P36zWi',
            'id': 28793787,
            'initiator': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'level': 479458,
            'nonce': 4,
            'sender': {'address': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa'},
            'status': 'applied',
            'storage': {'admin': 'tz1fbKDvLgwjnuXDcVDUW8JdPTAsna5VhvKD',
                        'ledger': 56870,
                        'metadata': 56871,
                        'paused': False,
                        'revenue': {'current_cycle': {'end_time': '2022-05-03T15:00:00Z',
                                                      'revenue': '882000',
                                                      'start_time': '2022-05-01T15:00:00Z',
                                                      'xtz_per_sec': '208333333333333333333'},
                                    'cycle_duration': '172800',
                                    'last_update': '2022-05-01T15:00:00Z',
                                    'multiplier': '100000000000000000000',
                                    'total_gif': '0',
                                    'xtz_per_gif': '0'},
                        'staking': {'collector': 'KT1XQqoUJUg5aYz8FjFiYUPegmcmSsuFxDcY',
                                    'gif': {'address': 'KT1TCcUZ32eHtBdj9CiXyqnvqFC9GwWfKReS',
                                            'token_id': '0'},
                                    'min_lock_amount': {'1': '5000000000000',
                                                        '2': '25000000000000',
                                                        '3': '100000000000000'},
                                    'revenue_tier': '3',
                                    'unlock_fees': {'1800': '1000',
                                                    '2700': '500',
                                                    '900': '4000'}}},
            'storageFee': 0,
            'storageLimit': 0,
            'storageUsed': 0,
            'target': {'address': 'KT1TeurBKDnhfyzUkeXWyCN9qbYpRRoFJNSF'},
            'timestamp': '2022-05-03T13:17:15Z',
            'type': 'transaction'},
           {'allocationFee': 0,
            'amount': 58200,
            'bakerFee': 0,
            'block': 'BLoXbfT3kujJ4Dp1XSgtiKCHpgDqsFFDnkU5MivPJ1YpmNRdBRm',
            'counter': 10356524,
            'gasLimit': 0,
            'gasUsed': 1420,
            'hasInternals': False,
            'hash': 'oob4msjXo19SF14YoVmrJ9Bn59ocA8LBt46yTUEbCGDG7P36zWi',
            'id': 28793788,
            'initiator': {'address': 'tz1ReP6Pfzgmcwm9rTzivdJwnmQm4KzKS3im'},
            'level': 479458,
            'nonce': 5,
            'sender': {'address': 'KT1CfhVyVnwLnwjfZL6dY4mRNxDVbGnZCkqa'},
            'status': 'applied',
            'storageFee': 0,
            'storageLimit': 0,
            'storageUsed': 0,
            'target': {'address': 'tz1fbKDvLgwjnuXDcVDUW8JdPTAsna5VhvKD'},
            'timestamp': '2022-05-03T13:17:15Z',
            'type': 'transaction'}],
  'state': 479458,
  'type': 1}]

analyse(testJson)